export const productsData = [
  {
    id: 1,
    description: "Product 1",
    price: "$20",
    state: "available",
  },
  {
    id: 2,
    description: "Product 2",
    price: "$30",
    state: "not available",
  },
  {
    id: 3,
    description: "Product 3",
    price: "$40",
    state: "available",
  },
  {
    id: 4,
    description: "Product 4",
    price: "$50",
    state: "available",
  },
  {
    id: 5,
    description: "Product 5",
    price: "$60",
    state: "available",
  },
  {
    id: 6,
    description: "Product 6",
    price: "$70",
    state: "available",
  },
  {
    id: 7,
    description: "Product 7",
    price: "$80",
    state: "available",
  },
  {
    id: 8,
    description: "Product 8",
    price: "$90",
    state: "not available",
  },
  {
    id: 9,
    description: "Product 9",
    price: "$100",
    state: "available",
  },
  {
    id: 10,
    description: "Product 10",
    price: "$110",
    state: "available",
  },
  {
    id: 11,
    description: "Product 11",
    price: "$120",
    state: "available",
  },
  {
    id: 12,
    description: "Product 12",
    price: "$130",
    state: "not available",
  },
  {
    id: 13,
    description: "Product 13",
    price: "$140",
    state: "not available",
  },
  {
    id: 14,
    description: "Product 14",
    price: "$150",
    state: "not available",
  },
  {
    id: 15,
    description: "Product 15",
    price: "$160",
    state: "available",
  },
];
